### ISSUE TITLE
Ability to preview images in tmux

### ISSUE THREAD

**Issue by BigBrotherJu** [benjajaja/ratatui-image#22]
Image preview in tmux is doable for kitty using unicode placeholder, not sure about other terminal emulators.

Currently, tmux(3.4) image preview is not working in joshuto(0.9.8)+kitty(0.33.1). The preview column does not display anything.

**Comment by benjajaja** [comment]
Should work with #19, I will make a PR on joshuto.

**Comment by benjajaja** [comment]
made a PR https://github.com/kamiyaa/joshuto/pull/553

**Comment by ErrorNoInternet** [comment]
Hi, I'm still not seeing anything in tmux 3.4 + kitty 0.36.1 on the main branch (297efaa75f082fee3d6741f53370fd00782e5244) of joshuto and iamb 0.0.10.

When I select a message in iamb, the image gets highlighted too, but I still can't see the actual image.

![image](https://github.com/user-attachments/assets/a2f0b786-b2cd-4e33-a29f-f83d64c0389c)

**Comment by Nemo157** [comment]
I think the `\x1bPtmux` etc. modifications need to be applied to the string generated in `kitty::transmit_virtual`, at least it looks like `kitten icat` is doing something similar when I inspect its output.
