### ISSUE TITLE
guess_protocol() falls back to Halfblocks on Windows Terminal (Preview)

### ISSUE THREAD

**Issue by matthias-buttgereit** [benjajaja/ratatui-image#37]
Windows Terminal (Preview) supports Sixel as of 1.22 (https://github.com/microsoft/terminal/releases). 

When running code inside WSL it does actually display images using Sixel but outside of WSL it falls back to Halfblocks.

| Windows Terminal (Preview) without WSL | Windows Terminal (Preview) with WSL |
| --- | --- |
| ![Screenshot 2024-08-29 191116](https://github.com/user-attachments/assets/72eea60d-f2ea-40a9-af96-31dfe0d31799) | ![Screenshot 2024-08-29 191146](https://github.com/user-attachments/assets/398ecad1-2f0a-4df0-925e-788ded4eb1f1) |

My guess is that the `guess_protocol()` function is not testing for Sixel support under Windows. Not sure if there is a way to do it yet but would be great if it could be added.

**Comment by j4james** [comment]
FYI, there is a bug in the latest Windows Terminal preview that affects VT reports in applications that don't enable VT input mode (see https://github.com/microsoft/terminal/issues/17813). It's possible that might be why it's not working outside WSL. VT input mode is set automatically in WSL, but that isn't the case for regular Windows console applications, unless they set the mode themselves, and I don't think the crossterm library does that.

**Comment by matthias-buttgereit** [comment]
Seems like Sixel is working in Windows Terminal (Preview) even without WSL when you manually cycle through the protocols (like in the demo example).

![Screenshot 2024-09-10 175542](https://github.com/user-attachments/assets/6cb7a878-3ce1-4353-929b-44e03647e129)

Just showing some weird behaviour when resizing (not fully clearing the area) but that might be a problem on the Windows Terminal part.

**Comment by benjajaja** [comment]
@matthias-buttgereit the weird behaviour is most likely an incorrect font-size, which should now be guessed correctly on WSL on master.

**Comment by benjajaja** [comment]
@matthias-buttgereit this should work on master now.
