### ISSUE TITLE
Is it possible to center the image in the panel

### ISSUE THREAD

**Issue by blacktop** [benjajaja/ratatui-image#38]
I was reading the kitty proto and it seems like it'd be possible to center the image in the panel, which would be more ascetically pleasing imho ;)

**Comment by benjajaja** [comment]
Do you mean centering relative to the borders that are produced when the image is resized? Or when cropped? Or something else entirely?

**Comment by benjajaja** [comment]
Closing as right now it's not possible to center neither fix nor crop options. But it could be implemented.

**Comment by blacktop** [comment]
Ya essentially adding CSS padding around the image so when resizing to keep it centered in the TUI panel (and also possibly when resize like in your example GIF)
