### ISSUE TITLE
Take a look at yazi

### ISSUE THREAD

**Issue by joshka** [benjajaja/ratatui-image#5]
Hey,
I noticed that [yazi](https://github.com/sxyazi/yazi) has a fairly comprehensive image display module that might be worth drawing some inspiration / code from (it's MIT licensed).

Specifically start at https://github.com/sxyazi/yazi/blob/main/adaptor/src/adaptor.rs and then look at how it progresses from there to image then {iterm2,kitty,sixel,uberzug} There's some logic that seems specific to the yazi app loading and caching files, but the core of this seems pretty robust.

Pinging @sxyazi for awareness

P.s. I wonder if you'd want to change the name this project to ratatui-image rather than ratatu-image for discoverability and eventual inclusion in the ratatui-org github org? (My fat fingers were surprised when https://crates.io/crate/ratatui-image was 404).

**Comment by sxyazi** [comment]
Hi @joshka, thanks for your appreciation of Yazi. I'm more than happy to see Yazi's code being used, and If there's anything I can do to help, please feel free to ask!

Finally, I'd like to thank you for your hard work on Ratatui; it's a great project, and it's because of Ratatui that Yazi exists!

**Comment by benjajaja** [comment]
Thank you @joshka! I can definitely use yazi's code for the missing implementations here and general reference.

I will change the crate's name for discoverability, thanks for the suggestion.
