### ISSUE TITLE
[BUG] On some terminals, images clear the foreground color

### ISSUE THREAD

**Issue by JoshuaVandaele** [benjajaja/ratatui-image#60]
From left to right: Kitty & Konsole

![image](https://github.com/user-attachments/assets/7c55df7c-0116-44b0-856e-f693c158c544)

I've also tested it with Alacritty, Foot, and Wezterm, in which case such problems don't occur.
I'm not able to test if the problem occurs on Windows' terminal or WSL.
Removing the image instantly clears the issue.

I have also noticed that "moving" text (text which is added after the image has been rendered for the first time) seems to adapt the correct color, even if it's discolored at first.

**Comment by benjajaja** [comment]
This is basically #42, it doesn't look like there is a workaround, you could ask on Kitty's project if there is a way to use anything else to encode the image id, like "underline color" which is Kitty proprietary, but it seems reserved for "placement id".

**Comment by kovidgoyal** [comment]
No, if you use unicode placeholders you have to use foreground color for id. Although I dont really understand why that's a problem. What is preventing you from resetting the foreground color after outputting the unicode placeholder chars, the same way you would if you output say, a word in a different color than the rest of the text.

**Comment by benjajaja** [comment]
@kovidgoyal because we don't know what the fg color before the image was.

**Comment by kovidgoyal** [comment]
So emit the escape code to save the colors, then emit the image and then
emit the escape code to restore the colors. The escape code is
XTPUSHCOLORS and XTPOPCOLORS.

https://sw.kovidgoyal.net/kitty/color-stack/

**Comment by kovidgoyal** [comment]
Actually, that wont work what you need is to save the currently used foreground and underline colors not the color table. That happens with the save/restore cursor escape codes. Note that restoring the cursor will also restore its position so you will need to manually reposition it after but that you can do since you know how many chars you have emitted.

**Comment by benjajaja** [comment]
Thanks a lot @kovidgoyal! This seems to work, at least with the demo. I added some surrounding fg colors in the demo so that this should be more easily testable from now on.
