### ISSUE TITLE
Scale and fit doesn't always resize properly

### ISSUE THREAD

**Issue by TadoTheMiner** [benjajaja/ratatui-image#62]
While developing #61 we noticed that fit and scal doesn't always resize properly. 
![image](https://github.com/user-attachments/assets/702187ea-5826-4022-9b4f-03c70d95d1e1)

**Comment by benjajaja** [comment]
Should be fixed in aebdd658befca2429b086cbb4fbbcf4da141e95f, but feel free to re-open if you spot any more problems.
