### ISSUE TITLE
Update the gif

### ISSUE THREAD

**Issue by TadoTheMiner** [benjajaja/ratatui-image#63]
As I said in #61 we should update the gif as new resize option has been added. I guess use https://github.com/charmbracelet/vhs

**Comment by benjajaja** [comment]
Sadly, vhs doesn't work at all.

**Comment by TadoTheMiner** [comment]
So our only option is to screen record with obs studio or similar?

**Comment by benjajaja** [comment]
Yea, I just used some random tool to create the showcase gif. If I find some time I'll update the gif, it looks a bit bad in general (xterm). If you want, you can also do it and send the gif.

On a tangent, I would really like to have some automated visual tests, but the best I could do is the xvfb screenshot test in the CI. Kitty and wezterm refuse to run under xvfb, and there's `weston` for wayland (I personally use wayland now) but I couldn't make it work to take screenshots/videos of terminals.

**Comment by benjajaja** [comment]
I needed to make a gif for https://github.com/benjajaja/mdfried/, so I updated the gif here as well.
